services:
  - type: web
    name: firesafety-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /ping
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://aroun-fires.onrender.com
      - key: APP_KEY
        value: base64:mUJm+3sEaSxkCOzjYPZenmwN/7HLxk7w2wCjrAudLN0=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 30265r.h.filess.io
      - key: DB_PORT
        value: "61001"
      - key: DB_DATABASE
        value: aroun_fires_db_exceptplay
      - key: DB_USERNAME
        value: aroun_fires_db_exceptplay
      - key: DB_PASSWORD
        value: 0bd939271134f981e637cad4815f792a2a2192bb
