services:
  - type: web
    name: firesafety-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /ping
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://firesafety-backend-7q42.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
